
server:
  port: 8080


spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/quartz
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #schema: classpath:schema/tables-${spring.datasource.platform}.sql

  quartz:
    jdbc:
      initialize-schema: embedded
    job-store-type: jdbc

mybatis:
  mapper-locations: mappers/**Mapper.xml
  type-aliases-package: com.lodumani

